### ISSUE TITLE
Missing WORKDIR leads to building failure

### ISSUE THREAD

**Issue by julianxhokaxhiu** [canthefason/go-watcher#11]
I was testing your Docker right now and I was having a weird issue. Even if I mapped the Volume correctly, I was having this output by `watcher`:

```
can't load package: package .: no buildable Go source files in /go
```

Then after some trials, I found that the issue was mainly because you're missing the `WORKDIR` declaration in the Dockerfile.

For now I fixed it by declaring it on the `docker run` command line, although would be nice to have it directly there.

Thanks again and keep up with this awesome project :)

**Comment by canthefason** [comment]
It seems that I added this WORKDIR a while ago (https://github.com/canthefason/go-watcher/pull/14), but forgot to respond to this issue. 😐 

Other than that thank you so much for your support! 😄
