### ISSUE TITLE
Wrong test labelling

### ISSUE THREAD

**Issue by julianxhokaxhiu** [canthefason/go-watcher#12]
I was reading the unit test file you've made, and I found a wrong labelling I guess.

At [this line](https://github.com/canthefason/go-watcher/blob/master/watch_test.go#L60) you wrote:
```
expected true, got false
```
for the .md file. But I guess it should be ( looking at the IF condition ):
```
expected false, got true
```
right?

**Comment by canthefason** [comment]
Hey, nice catch! 👍 Thank you so much!
