### ISSUE TITLE
Add ability to run with -race

### ISSUE THREAD

**Issue by arp242** [canthefason/go-watcher#19]
As far as I can see there is no option to build Go binaries with the `-race` flag set; the `go build` command is hard-coded as:

    cmd, err := runCommand("go", "build", "-i", "-o", fileName, pkg)

did I miss something?

Could this option be added? Perhaps it would be good to allow passing arbitrary flags to `go build`; maybe after `--`?

    watcher -c appflag -run example.com/pkg -- -race

Or maybe something like?

    watcher -c appflag -run example.com/pkg -buildflags '-race'

**Comment by snarlysodboxer** [comment]
Other flags are needed too, E.G. `-tags`.
