### ISSUE TITLE
Slow down building process a bit?

### ISSUE THREAD

**Issue by importnil** [canthefason/go-watcher#3]
Great tool, though there's one big problem. I use other watcher (go-razor's templates watcher) which builds .go templates on change, but seems like 99% of the time go-watcher can't yet get changed templates so it rebuilds with an old version. Maybe there's a quick fix (timeout) for this? Thanks.

**Comment by canthefason** [comment]
Sorry, I couldn't reply back, kinda busy days! I didn't use this watcher with templates, nevertheless I will try to fix that over the weekend.

**Comment by canthefason** [comment]
A while ago I increased the watcher delay https://github.com/canthefason/go-watcher/commit/eaba2b43b73ad8ba9f2386c8f9b0431a16243616, but looks like I did not update this issue. Hope it works for you, and sorry for my very late response.
