### ISSUE TITLE
Dockerfile without VOLUME

### ISSUE THREAD

**Issue by julianxhokaxhiu** [canthefason/go-watcher#6]
I was wondering how to use your Docker, if you didn't declare a Volume. Which will be the path that it will watch? Can you add support for Volumes? Would be a nice-to-have feature :)

Best regards,
Julian

**Comment by canthefason** [comment]
Running it in a container was an experimental feature, and looks like I forgot to put Volume declaration in the Dockerfile. I would really appreciate any kinds of feedback about the containerized version. 

And inevitably I also need to work on the issue #9 to extend supported Go versions.

**Comment by julianxhokaxhiu** [comment]
Thank you! I saw your addition. I'll try to use it now and I'll give some proper feedback to you :)

Best regards!
