### ISSUE TITLE
Support different versions of Go in the containerized version

### ISSUE THREAD

**Issue by canthefason** [canthefason/go-watcher#9]
Currently, we only have support for Go Version 1.6.3. We need to extend it and add support for other versions, as well.

**Comment by julianxhokaxhiu** [comment]
I suggest to use tags, and automatically trigger the build process on Docker Hub. So if I need `1.6.3` I'll fetch the docker image with tag `1.6.3`.

Of course if 1.6.x is still a living version, consider doing a branch per version, until it's considered deprecated.

By default, always consider the latest version. Thanks!
